name: Trigger auto deployment for hotelservice

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/hotelservice-AutoDeployTrigger-b532913a-0a99-450f-b62a-49d376c29cfe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HOTELSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOTELSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOTELSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: devopsaziz2.azurecr.io
          registryUsername: ${{ secrets.HOTELSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOTELSERVICE_REGISTRY_PASSWORD }}
          containerAppName: hotelservice
          resourceGroup: devops-rg
          imageToBuild: devopsaziz2.azurecr.io/hotelservice:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


