name: Test, Build, Deploy Test Stage and E2E for HotelService

on:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  ACR_NAME: devopsaziz2
  TEST_ENV: "test"
  E2E_ENV: "e2e"

jobs:
  test-and-build:
    runs-on: self-hosted
    env:
      ACR_USERNAME: ${{ secrets.HOTELSERVICE_REGISTRY_USERNAME }}
      ACR_PASSWORD: ${{ secrets.HOTELSERVICE_REGISTRY_PASSWORD }}
      IMAGE_NAME: hotel_service
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Run unit and integration tests
        run: mvn test --no-transfer-progress

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=AzizRahali_ME_Pipeline
            -Dsonar.organization=azizrahali
            -Dsonar.java.binaries=target
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TEST_ENV }}

  deploy-test:
    needs: test-and-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      CONTAINER_APP_NAME: hotelservice-test
      RESOURCE_GROUP: devops-rg
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HOTELSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOTELSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOTELSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Test Version to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ env.ACR_NAME }}.azurecr.io
          registryUsername: ${{ secrets.HOTELSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOTELSERVICE_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TEST_ENV }}