name: Test, Build, Deploy Test Stage and E2E for HotelService

on:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  ACR_NAME: devopsaziz2
  IMAGE_NAME: hotel_service
  TEST_ENV: "test"
  E2E_ENV: "e2e"

jobs:

  build-and-test:
    name: Build Maven and Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Run tests with JaCoCo coverage
        run: mvn clean verify -Pcoverage --no-transfer-progress

  sonarqube-analysis:
    name: SonarQube Analysis
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile code (for SonarQube)
        run: mvn compile --no-transfer-progress

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=AzizRahali_ME_Pipeline
            -Dsonar.organization=azizrahali
            -Dsonar.java.binaries=target
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-build-push:
    name: Build and Push Docker Image
    needs: sonarqube-analysis
    runs-on: self-hosted
    env:
      ACR_USERNAME: ${{ secrets.HOTELSERVICE_REGISTRY_USERNAME }}
      ACR_PASSWORD: ${{ secrets.HOTELSERVICE_REGISTRY_PASSWORD }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TEST_ENV }}

  deploy-test:
    name: Deploy to Test Environment
    needs: docker-build-push
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    env:
      CONTAINER_APP_NAME: hotelservice-test
      RESOURCE_GROUP: devops-rg
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HOTELSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HOTELSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HOTELSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ${{ env.ACR_NAME }}.azurecr.io
          registryUsername: ${{ secrets.HOTELSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HOTELSERVICE_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TEST_ENV }}
